// src/main/java/com/example/Db.java
package com.example;

import java.sql.*;

public class Db {
    private static Connection conn;

    /** Devuelve la conexión singleton a H2 */
    public static Connection get() {
        if (conn == null) init();
        return conn;
    }

    /** Inicializa H2 y asegura el esquema */
    private static void init() {
        try {
            Class.forName("org.h2.Driver");
            // Base de datos de archivo en ./data/collectibles (modo PostgreSQL para compatibilidad SQL)
            conn = DriverManager.getConnection(
                    "jdbc:h2:./data/collectibles;MODE=PostgreSQL", "sa", "");
            ensureSchema(conn);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /** Crea tablas si no existen y agrega semillas mínimas */
    private static void ensureSchema(Connection c) throws SQLException {
        try (Statement st = c.createStatement()) {
            // ---- USERS
            st.execute("""
                CREATE TABLE IF NOT EXISTS users(
                  id    VARCHAR(40) PRIMARY KEY,
                  name  VARCHAR(120) NOT NULL,
                  email VARCHAR(255) NOT NULL
                )
                """);

            // ---- PRODUCTS
            st.execute("""
                CREATE TABLE IF NOT EXISTS products(
                  id        VARCHAR(40) PRIMARY KEY,
                  name      VARCHAR(120) NOT NULL,
                  descr     VARCHAR(2000),
                  image_url VARCHAR(500),
                  price     DECIMAL(12,2) NOT NULL,
                  stock     INT NOT NULL
                )
                """);

            // ---- ORDERS (corregido para H2 2.x: usar GENERATED ... AS IDENTITY)
            st.execute("""
                CREATE TABLE IF NOT EXISTS orders(
                  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  user_id    VARCHAR(40) NOT NULL,
                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  total      DECIMAL(12,2) NOT NULL,
                  CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users(id)
                )
                """);

            // ---- ORDER_ITEMS (corregido para H2 2.x)
            st.execute("""
                CREATE TABLE IF NOT EXISTS order_items(
                  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  order_id   BIGINT NOT NULL,
                  product_id VARCHAR(40) NOT NULL,
                  qty        INT NOT NULL,
                  price      DECIMAL(12,2) NOT NULL,
                  CONSTRAINT fk_item_order  FOREIGN KEY (order_id)  REFERENCES orders(id),
                  CONSTRAINT fk_item_prod   FOREIGN KEY (product_id) REFERENCES products(id)
                )
                """);
        }

        // ---- Semillas: users
        try (var rs = c.createStatement().executeQuery("SELECT COUNT(*) FROM users")) {
            rs.next();
            if (rs.getLong(1) == 0) {
                c.createStatement().executeUpdate("""
                    INSERT INTO users(id,name,email) VALUES
                    ('1','Rafael','rafael@example.com'),
                    ('2','Sofía','sofia@example.com')
                    """);
            }
        }

        // ---- Semillas: products
        try (var rs = c.createStatement().executeQuery("SELECT COUNT(*) FROM products")) {
            rs.next();
            if (rs.getLong(1) == 0) {
                c.createStatement().executeUpdate("""
                    INSERT INTO products(id,name,descr,image_url,price,stock) VALUES
                    ('p1','Figura Goku','SSJ Blue 15cm',NULL, 499.00, 10),
                    ('p2','Carta Pikachu','Holo 1st ed',NULL, 1299.00, 5)
                    """);
            }
        }
    }
}
